name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Check formatting
        run: dotnet format --verify-no-changes

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract project version
        id: project-version
        run: |
          VERSION=$(grep -oP '<Version>\\K[^<]+' src/Moongate.Server/Moongate.Server.csproj || echo "0.0.1")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t tgiachi/moongate:latest -t tgiachi/moongate:${{ steps.project-version.outputs.VERSION }} .

      - name: Push Docker image
        run: |
          docker push tgiachi/moongate:latest
          docker push tgiachi/moongate:${{ steps.project-version.outputs.VERSION }}
